import React from 'react';
import { createRoot } from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { motion } from 'framer-motion';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Bell, Bot, Brain, CheckCircle2, ChevronRight, Inbox, LifeBuoy, Moon, Search, Settings, ShieldAlert, Sparkles, Sun, Users, type LucideIcon } from 'lucide-react';
import { categories, emails, escalations, kpis, sentiment, volume } from './lib/data';
import { useUiStore } from './store/ui';
import './styles.css';
const nav: Array<[string, LucideIcon]> = [['Dashboard', Bot], ['Inbox', Inbox], ['Escalations', ShieldAlert], ['Knowledge Base', Brain], ['Analytics', Sparkles], ['Team Management', Users], ['Settings', Settings]];
const colors = ['#8b5cf6', '#06b6d4', '#22c55e', '#f59e0b', '#ef4444', '#64748b'];
function App() { const { theme, toggleTheme } = useUiStore(); return <div className={theme}><main className="min-h-screen bg-slate-50 text-slate-950 dark:bg-[#070910] dark:text-white"><div className="flex">
  <aside className="hidden min-h-screen w-72 border-r border-slate-200/70 bg-white/70 p-5 backdrop-blur-xl dark:border-white/10 dark:bg-white/[0.03] lg:block"><div className="mb-8 flex items-center gap-3"><div className="rounded-2xl bg-violet-600 p-2"><Bot /></div><div><h1 className="font-semibold">MailPilot AI</h1><p className="text-xs text-slate-500">Customer automation</p></div></div><nav className="space-y-1">{nav.map(([n, Icon]) => <a className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-white/10" key={n}><Icon size={18}/>{n}</a>)}</nav><div className="mt-10 rounded-3xl border border-violet-500/20 bg-violet-500/10 p-4"><Sparkles className="text-violet-400"/><h3 className="mt-3 font-medium">RAG confidence</h3><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">97.2% grounded against 1,284 KB chunks.</p></div></aside>
  <section className="flex-1 p-4 lg:p-8"><header className="mb-8 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm text-violet-500">Enterprise support automation</p><h2 className="text-3xl font-semibold tracking-tight">AI Email Command Center</h2></div><div className="flex items-center gap-3"><div className="relative"><Search className="absolute left-3 top-2.5 text-slate-400" size={18}/><input className="rounded-2xl border border-slate-200 bg-white py-2 pl-10 pr-4 dark:border-white/10 dark:bg-white/5" placeholder="Search inbox"/></div><button onClick={toggleTheme} className="rounded-2xl border border-slate-200 p-2.5 dark:border-white/10">{theme==='dark'?<Sun/>:<Moon/>}</button><button className="rounded-2xl bg-violet-600 px-4 py-2 font-medium text-white">Connect Gmail</button></div></header>
  <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-6">{kpis.map(([label,value,delta], i)=><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{delay:i*.04}} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/[0.04]" key={label}><p className="text-sm text-slate-500">{label}</p><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-2 text-sm text-emerald-500">{delta}</p></motion.div>)}</div>
  <div className="mt-6 grid gap-6 xl:grid-cols-3"><Panel title="Email volume" wide><ResponsiveContainer height={280}><LineChart data={volume}><CartesianGrid strokeDasharray="3 3" opacity=.15/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line dataKey="received" stroke="#8b5cf6" strokeWidth={3}/><Line dataKey="replied" stroke="#06b6d4" strokeWidth={3}/><Line dataKey="escalated" stroke="#ef4444" strokeWidth={3}/></LineChart></ResponsiveContainer></Panel><Panel title="Category distribution"><ResponsiveContainer height={280}><PieChart><Pie data={categories} dataKey="value" innerRadius={60} outerRadius={95}>{categories.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Panel><Panel title="Sentiment trends" wide><ResponsiveContainer height={260}><AreaChart data={sentiment}><XAxis dataKey="day"/><YAxis/><Tooltip/><Area dataKey="happy" stackId="1" stroke="#22c55e" fill="#22c55e66"/><Area dataKey="frustrated" stackId="1" stroke="#f59e0b" fill="#f59e0b66"/><Area dataKey="angry" stackId="1" stroke="#ef4444" fill="#ef444466"/></AreaChart></ResponsiveContainer></Panel><Panel title="Response time"><ResponsiveContainer height={260}><BarChart data={volume}><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="replied" fill="#8b5cf6" radius={[8,8,0,0]}/></BarChart></ResponsiveContainer></Panel></div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_380px]"><Panel title="Inbox management" wide><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-slate-500"><tr>{['Sender','Subject','Category','Sentiment','Confidence','Status','Received'].map(h=><th className="px-3 py-3" key={h}>{h}</th>)}</tr></thead><tbody>{emails.map(e=><tr className="border-t border-slate-200 dark:border-white/10" key={e.subject}><td className="px-3 py-4 font-medium">{e.sender}</td><td className="px-3 py-4">{e.subject}</td><td><Badge>{e.category}</Badge></td><td className="px-3 py-4">{e.sentiment}</td><td className="px-3 py-4">{e.confidence}%</td><td><Badge>{e.status}</Badge></td><td className="px-3 py-4 text-slate-500">{e.time}</td></tr>)}</tbody></table></div></Panel><Panel title="Escalation center"><div className="space-y-3">{escalations.map((e,i)=><div className="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 dark:border-white/10" key={e}><ShieldAlert className="text-rose-400"/><div className="flex-1"><p className="text-sm font-medium">{e}</p><p className="text-xs text-slate-500">Rule #{i+1} · assign owner</p></div><ChevronRight size={18}/></div>)}</div></Panel></div>
  <div className="mt-6 grid gap-6 lg:grid-cols-3"><Feature icon={<LifeBuoy/>} title="Approval mode" text="Agents review, edit, approve, send, escalate, or reclassify every AI draft."/><Feature icon={<CheckCircle2/>} title="Auto-send guardrails" text="Legal, VIP, sensitive attachments, and low confidence messages never auto-send."/><Feature icon={<Bell/>} title="Slack & Teams alerts" text="Escalations notify humans in-app, by email, and through collaboration webhooks."/></div>
  </section></div></main></div> }
function Panel(p:{title:string;wide?:boolean;children:React.ReactNode}){return <section className={`rounded-3xl border border-slate-200 bg-white p-5 shadow-sm dark:border-white/10 dark:bg-white/[0.04] ${p.wide?'xl:col-span-2':''}`}><h3 className="mb-4 font-semibold">{p.title}</h3>{p.children}</section>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-medium dark:bg-white/10">{children}</span>}
function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-3xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-white/[0.04]"><div className="text-violet-400">{icon}</div><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">{text}</p></div>}
createRoot(document.getElementById('root')!).render(<QueryClientProvider client={new QueryClient()}><App /></QueryClientProvider>);
